CREATE DATABASE IF NOT EXISTS evangadi_forum
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE evangadi_forum;

CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  questionid VARCHAR(32) NOT NULL UNIQUE,
  userid INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  tag VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_questions_user
    FOREIGN KEY (userid) REFERENCES users(user_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answers (
  answerid INT AUTO_INCREMENT PRIMARY KEY,
  userid INT NOT NULL,
  questionid INT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_answers_user
    FOREIGN KEY (userid) REFERENCES users(user_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_answers_question
    FOREIGN KEY (questionid) REFERENCES questions(id)
    ON DELETE CASCADE
);

CREATE INDEX idx_questions_userid ON questions(userid);
CREATE INDEX idx_answers_questionid ON answers(questionid);
